title: 'Introduction to Machine Learning'
description: Welcome to ECE421
theme: just-the-docs

url: https://erfanmeskar.github.io/ece421

aux_links:
  Template Repository: https://erfanmeskar.github.io/ece421
